"""Validate the hand-curated SEBI structural-event timeline and publish it to data/raw/.

The charter requires this timeline to live in ``data/raw/`` with a ``.meta.json`` citing each
source. It does. But the *canonical* copy is version-controlled at
``benchmarks/regimestress/sebi_events.csv``, and this script copies it outward — a deliberate
departure from the usual direction of travel, for one reason:

``data/`` is gitignored. Every other file in ``data/raw/`` is re-fetchable from a URL, so losing it
costs a download. This one is hand-curated from primary circulars; if it existed only there, a
single ``rm -rf data/`` would destroy work that cannot be regenerated by running anything. The
charter's requirement is about *where the pipeline reads it from*, which is honoured.

Validation is the point of this script, not the copy. It refuses to publish a timeline where a date
does not parse, a source URL is missing, or an effective date precedes its announcement — the
failure modes a hand-edited CSV actually has.

Usage:
    python scripts/build_sebi_events.py
"""

from __future__ import annotations

import sys
from datetime import date

import polars as pl

from src.common.config import load_config
from src.common.io import write_raw_parquet
from src.common.log import get_logger
from src.common.manifest import RunManifest
from src.stress.events import SOURCE_CSV, load_events

_log = get_logger(__name__)

OUTPUT_NAME = "sebi_events.parquet"

def main() -> int:
    cfg = load_config()
    if not SOURCE_CSV.exists():
        _log.error("%s not found", SOURCE_CSV)
        return 1

    frame = load_events()

    dev_start = date.fromisoformat(str(cfg.raw["dates"]["dev_start"]))
    dev_end = date.fromisoformat(str(cfg.raw["dates"]["dev_end"]))
    in_window = frame.filter(
        (pl.col("effective_date") >= dev_start) & (pl.col("effective_date") <= dev_end)
    )

    path = cfg.paths.data_raw / OUTPUT_NAME
    with RunManifest(cfg, script="build_sebi_events.py") as run:
        run.add_input(SOURCE_CSV)
        # write_raw_parquet refuses to overwrite, so republishing an edited timeline is a
        # deliberate act: delete the old file and say why. data/raw/ stays write-once.
        write_raw_parquet(
            frame,
            path,
            source_url=f"hand-curated; canonical copy at {SOURCE_CSV.as_posix()}",
            extra={
                "purpose": "SEBI / market-structure event timeline for Phase 2.0 regime labelling",
                "curated_on": "2026-08-01",
                "n_events": frame.height,
                "n_effective_in_development_window": in_window.height,
                "development_window": f"{dev_start} .. {dev_end}",
                "evidence_breakdown": {
                    str(row["evidence"]): row["len"]
                    for row in frame.group_by("evidence").len().iter_rows(named=True)
                },
                "known_gaps": [
                    "Macroeconomic and fiscal events are out of scope: demonetisation "
                    "(Nov 2016), GST introduction (Jul 2017), the reintroduction of LTCG on "
                    "equities (Budget 2018) and COVID lockdown dates are NOT in this file.",
                    "The CNX-to-NIFTY index renaming is observable in the NSE index bhavcopy "
                    "during 2015 but no announcement date was sourced, so it is omitted rather "
                    "than dated from inference.",
                    "NIFTY broad-market index reconstitution is periodic, not a one-off event: "
                    "semi-annual in March and September on six-month data ending 31 January and "
                    "31 July, four weeks' notice, implemented the first working day after the "
                    "March/September F&O expiry. Recorded here rather than as dated rows because "
                    "the individual reconstitution dates were not sourced. Source: "
                    "https://niftyindices.com/Methodology/Method_NIFTY_Equity_Indices.pdf",
                    "This timeline is NOT claimed to be exhaustive. It is what could be sourced "
                    "to a circular number or a primary document on 2026-08-01.",
                ],
            },
        )
        run.note("n_events", frame.height)
        run.note("n_in_development_window", in_window.height)

    print(f"{frame.height} events validated and written to {path}")
    print(f"{in_window.height} take effect inside the development window {dev_start}..{dev_end}\n")
    print(frame.select("effective_date", "category", "title").to_pandas().to_string(index=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
