"""Emit the LaTeX macros the three papers share, from META.json. Never edited by hand.

The three papers were written when the programme had one generator and one prompting method. They
now share a generator axis (four models) and a methodology axis (six paradigms), and several of
their headline claims are joint claims across both. A number that appears in more than one paper
must be the same number, so it is defined once here and included by all three.

Naming: ``\pgm`` prefix, so a reader of any paper can tell at a glance which macros are
programme-level and which are that paper's own.

Usage:
    python scripts/build_programme_numbers.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # noqa: E402

from src.common.log import configure_logging, get_logger  # noqa: E402

_log = get_logger(__name__)

META = Path("benchmarks/generationbench/META.json")
OUT = Path("papers/programme_numbers.tex")

ARM_MACRO = {"G1": "Plain", "G2": "Cot", "G4": "Plan", "G5": "Reflect",
             "G6": "Graph", "G7": "Mcts"}


def _thousands(value: str) -> str:
    """Group a bare integer of four or more digits, so 2495 typesets as 2,495.

    Presentation only, applied at emission so no call site has to remember it. The papers state
    some counts inline and some through macros, and an unseparated 2495 beside a hand-written
    1,550 reads as two different quantities. Decimals, percentages, signed values and the ``--``
    placeholder are left exactly as they are.
    """
    if not value.isdigit() or len(value) < 4:
        return value
    return f"{int(value):,}"


def _pct(x: float | None) -> str:
    return "--" if x is None else f"{x * 100:.1f}"


def _num(x: float | None, places: int = 3) -> str:
    return "--" if x is None else f"{x:.{places}f}"


def main() -> int:
    configure_logging()
    meta = json.loads(META.read_text(encoding="utf-8"))
    lines = [
        "% GENERATED BY scripts/build_programme_numbers.py -- DO NOT EDIT BY HAND.",
        "% Programme-level numbers shared by all three papers, from benchmarks/"
        "generationbench/META.json.",
        "",
    ]

    def emit(name: str, value: str, source: str) -> None:
        lines.append(f"\\newcommand{{\\pgm{name}}}{{{_thousands(value)}}}  % {source}")

    null = meta["findings"]["auditor_abstention_null"]
    emit("NullCorpora", str(null["n_corpora"]), "auditor_abstention_null")
    emit("NullCombos", str(null["n_combinations_total"]), "auditor_abstention_null")
    emit("NullBeating", str(null["n_combinations_beating_random"]), "auditor_abstention_null")

    soph = meta["findings"]["sophistication_under_compute_matching"]
    emit("ScaffoldArms", str(soph["n_scaffolded_arms"]), "compute-matched control")
    emit("ScaffoldWins", str(soph["n_beating_control_on_yield"]), "compute-matched control")

    front = meta["findings"]["frontier_front_vs_back"]
    if front.get("available"):
        emit("LocalExec", _pct(front["front"]["reference_execution_rate"]), "G1 funnel")
        emit("LocalTrade", _pct(front["front"]["reference_position_taking_rate"]), "G1 funnel")
        emit("LocalHoldMed",
             _num(front["back"]["reference_holdout_median_sharpe"], 3), "G1 holdout")
        for label, rate in front["front"]["frontier_position_taking_rates"].items():
            emit(f"{label}Trade", _pct(rate), "frontier funnel")
        for label, rate in front["front"]["frontier_execution_rates"].items():
            emit(f"{label}Exec", _pct(rate), "frontier funnel")
        for label, med in front["back"]["frontier_holdout_median_sharpe"].items():
            emit(f"{label}HoldMed", _num(med, 3), "frontier holdout")

    # Per-paradigm, for the tables all three papers draw from.
    for record in meta["methodology_axis"]:
        key = ARM_MACRO[record["arm"]]
        funnel, cap = record["funnel"], record["capacity"]
        emit(f"{key}Draws", str(funnel["n_draws"]), "paradigm funnel")
        emit(f"{key}Exec", _pct(funnel["execution_rate"]), "paradigm funnel")
        emit(f"{key}Trade", _pct(funnel["position_taking_rate"]), "paradigm funnel")
        emit(f"{key}Surv", _pct(record["full_stack_survival"]), "funnel.json")
        emit(f"{key}DevMed", _num(funnel["dev_median_sharpe"]), "paradigm backtests")
        emit(f"{key}HoldMed", _num(funnel["holdout_median_sharpe"]), "paradigm holdout")
        emit(f"{key}HoldPos", _pct(funnel["holdout_fraction_positive"]), "paradigm holdout")
        emit(f"{key}Trials", str(record["trials_arm"]), "trial ledger")
        emit(f"{key}Pbo", _num(record["pbo"], 3), "audit_results")
        emit(f"{key}Knife", _pct(record["knife_edge_rate"]), "calibration")
        emit(f"{key}Frag", _num(record["fragility_tier2_across_regimes_median"]), "tier-2 stress")
        emit(f"{key}FragN", str(record["fragility_n"]), "tier-2 stress")
        emit(f"{key}CapMed", _num(cap["deployed_median_crore"], 2), "capacity, deployed")
        emit(f"{key}CapMax", _num(cap["deployed_max_crore"], 2), "capacity, deployed")
        emit(f"{key}CapN", str(cap["deployed_n"]), "capacity, deployed")
        emit(f"{key}NearCash", str(cap["near_cash_n"]), "exposure")
        emit(f"{key}Redund", _pct(record["redundancy_of_traded"]), "redundancy")
        emit(f"{key}PZero", _pct(record["p_zero_duplicates_at_reference_rate"]),
             "redundancy power")
        emit(f"{key}XArm", _pct(record["cross_arm_duplicate_share"]), "cross-arm duplicates")
        control = record["compute_matched"]
        emit(f"{key}K", str(control["k"]) if control["k"] else "--", "RULE 11 control")
        emit(f"{key}CtrlYield", _pct(control["control_yield"]), "RULE 11 control")
        emit(f"{key}TreatYield", _pct(control["treatment_yield"]), "RULE 11 control")
        if record["ablation_holdout"]:
            emit(f"{key}AuapBest", _num(record["ablation_holdout"]["best_auap"], 4), "ablation")
            emit(f"{key}AuapN", str(record["ablation_holdout"]["n_ranked"]), "ablation")

    pooled = json.loads(
        (Path("benchmarks/generationbench/corpus/G1/audit_results.json")).read_text(
            encoding="utf-8"))
    emit("PooledTrials", str(pooled["n_trials_pooled"]), "pooled trial ledger")

    total_draws = sum(r["funnel"]["n_draws"] for r in meta["methodology_axis"])
    emit("ParadigmDraws", str(total_draws), "sum of paradigm draws")
    emit("ParadigmArms", str(len(meta["methodology_axis"])), "methodology axis")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _log.info("wrote %d macros to %s", len(lines) - 3, OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
